# Generated by Django 5.2.4 on 2026-04-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edit_name',
            field=models.BooleanField(default=True, verbose_name='Изменять имя?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edit_username',
            field=models.BooleanField(default=True, verbose_name='Изменять имя пользователя?'),
        ),
    ]
