# Generated by Django 5.2.4 on 2026-04-16 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_edit_name_alter_user_edit_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('check_id', models.CharField(max_length=50, unique=True, verbose_name='ID проверки')),
                ('call_phone', models.CharField(max_length=20, verbose_name='Номер для звонка')),
                ('status', models.CharField(choices=[('pending', 'Ожидает звонка'), ('confirmed', 'Подтвержден'), ('expired', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Токен сброса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия восстановления пароля по звонку',
                'verbose_name_plural': 'Сессии восстановления пароля по звонку',
                'db_table': 'password_reset_call_session',
            },
        ),
    ]
