# Generated by Django 5.2.4 on 2026-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcallsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcallsession',
            name='check_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='ID проверки'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordresetcallsession',
            unique_together={('check_id', 'status')},
        ),
    ]
