# Generated by Django 5.2.4 on 2025-08-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(default=None, upload_to='color_images/', verbose_name='Изображение цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.color', verbose_name='Доступные цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='product_images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
