# Generated by Django 5.2.4 on 2025-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_color_image_alter_product_available_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='make_time',
            field=models.CharField(blank=True, default='30 мин', max_length=100, null=True, verbose_name='Время занятости'),
        ),
    ]
