# Generated by Django 5.2.4 on 2026-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_make_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_str',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для цены, если надо (за штуку)'),
        ),
    ]
