# Generated by Django 5.2.4 on 2026-04-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_appointment_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledate',
            options={'verbose_name': 'Даты для записи', 'verbose_name_plural': 'Даты для записи'},
        ),
    ]
