# Generated by Django 5.2.4 on 2026-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_availabledate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
