# Generated by Django 5.2.4 on 2026-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_appointment_day_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='отправка утром'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False, verbose_name='отправка за 2 часа'),
        ),
    ]
