# Generated by Django 5.2.4 on 2026-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_appointment_day_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.CreateModel(
            name='MyWorkDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sasha', 'Саша'), ('sveta', 'Света')], default='sasha', max_length=100, verbose_name='Имя')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('day_work', models.BooleanField(default=False, verbose_name='работает?')),
            ],
            options={
                'verbose_name': 'Даты для записи',
                'verbose_name_plural': 'Даты для записи',
                'unique_together': {('date',)},
            },
        ),
    ]
