# Generated by Django 5.2.4 on 2026-05-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_appointment_options_myworkdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myworkdate',
            options={'verbose_name': 'Не трогать', 'verbose_name_plural': 'Не трогать'},
        ),
        migrations.AlterUniqueTogether(
            name='myworkdate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='myworkdate',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='myworkdate',
            unique_together={('date', 'name')},
        ),
    ]
