# Generated by Django 5.2.4 on 2026-05-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_fix_unique_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyWorkDate',
        ),
    ]
